kind = "web"
previewPath = "/hotel-kailash/"
title = "Hotel Kailash"
version = "1.0.0"
id = "artifacts/hotel-kailash"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/hotel-kailash/" ]
localPort = 18419

[services.development]
run = "pnpm --filter @workspace/hotel-kailash run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hotel-kailash", "run", "build" ]
publicDir = "artifacts/hotel-kailash/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18419"
BASE_PATH = "/hotel-kailash/"
